/**
 * Path templates (from `openapi.yaml`, one `export const` per `operationId`).
 * Static paths are `as const` strings. Paths with `{param}` are functions: one `string` arg per
 * segment (e.g. `(toolset_name: string) => ...`) or a single object when there are several `{...}` parts.
 *
 * @generated by `scripts/generate-sdk-client.mjs` — do not edit by hand; run `npm run gen`
 */

export const acceptUserConsent = (deployment_id: string) => { return `/v1/consent/${deployment_id}` };

export const approvePublication = '/v1/ops/publication/approve';
export const callToolSet = (toolset_name: string) => { return `/v1/toolset/${toolset_name}/mcp` };

export const closeSession = '/v1/ops/code_interpreter/close_session';
export const configurationDeployment = (deployment_name: string) => { return `/v1/deployments/${deployment_name}/configuration` };

export const copyResource = '/v1/ops/resource/copy';
export const copySharedResources = '/v1/ops/resource/share/copy';
export const createPublication = '/v1/ops/publication/create';
export const deleteConversation = (bucket: string, conversation_path: string) => { return `/v1/conversations/${bucket}/${conversation_path}` };

export const deleteCustomApplication = (bucket: string, application_path: string) => { return `/v1/applications/${bucket}/${application_path}` };

export const deleteFile = (bucket: string, file_path: string) => { return `/v1/files/${bucket}/${file_path}` };

export const deleteInvitation = (invitation_id: string) => { return `/v1/invitations/${invitation_id}` };

export const deleteNotifications = '/v1/ops/notification/delete';
export const deletePrompt = (bucket: string, prompt_path: string) => { return `/v1/prompts/${bucket}/${prompt_path}` };

export const deletePublication = '/v1/ops/publication/delete';
export const deleteToolSet = (bucket: string, toolset_path: string) => { return `/v1/toolsets/${bucket}/${toolset_path}` };

export const deployApplication = '/v1/ops/application/deploy';
export const discardSharedResources = '/v1/ops/resource/share/discard';
export const downloadFile = (bucket: string, file_path: string) => { return `/v1/files/${bucket}/${file_path}` };

export const downloadFileFromCodeInterpreter = '/v1/ops/code_interpreter/download_file';
export const executeCode = '/v1/ops/code_interpreter/execute_code';
export const getApplication = (application_name: string) => { return `/openai/applications/${application_name}` };

export const getApplicationLogs = '/v1/ops/application/logs';
export const getApplicationMetadata = (bucket: string, path: string) => { return `/v1/metadata/applications/${bucket}/${path}` };

export const getApplications = '/openai/applications';
export const getConversation = (bucket: string, conversation_path: string) => { return `/v1/conversations/${bucket}/${conversation_path}` };

export const getConversationMetadata = (bucket: string, path: string) => { return `/v1/metadata/conversations/${bucket}/${path}` };

export const getCustomApplication = (bucket: string, application_path: string) => { return `/v1/applications/${bucket}/${application_path}` };

export const getCustomApplicationSchema = '/v1/application_type_schemas/schema';
export const getCustomToolSet = (bucket: string, toolset_path: string) => { return `/v1/toolsets/${bucket}/${toolset_path}` };

export const getDeployment = (deployment_name: string) => { return `/openai/deployments/${deployment_name}` };

export const getDeploymentLimits = (deployment_name: string) => { return `/v1/deployments/${deployment_name}/limits` };

export const getDeployments = '/openai/deployments';
export const getFileMetadata = (bucket: string, path: string) => { return `/v1/metadata/files/${bucket}/${path}` };

export const getInvitation = (invitation_id: string) => { return `/v1/invitations/${invitation_id}` };

export const getInvitations = '/v1/invitations';
export const getMetaSchemaOfCustomApplicationSchema = '/v1/application_type_schemas/meta_schema';
export const getModel = (model_name: string) => { return `/openai/models/${model_name}` };

export const getModels = '/openai/models';
export const getNotifications = '/v1/ops/notification/list';
export const getPerRequestPermissions = '/v1/ops/resource/per-request-permissions/list';
export const getPrompt = (bucket: string, prompt_path: string) => { return `/v1/prompts/${bucket}/${prompt_path}` };

export const getPromptMetadata = (bucket: string, path: string) => { return `/v1/metadata/prompts/${bucket}/${path}` };

export const getPublication = '/v1/ops/publication/get';
export const getPublicationRules = '/v1/ops/publication/rule/list';
export const getPublications = '/v1/ops/publication/list';
export const getSession = '/v1/ops/code_interpreter/get_session';
export const getSharedResources = '/v1/ops/resource/share/list';
export const getToolSetMetadata = (bucket: string, path: string) => { return `/v1/metadata/toolsets/${bucket}/${path}` };

export const getToolSets = '/openai/toolsets';
export const getToolset = (toolset_name: string) => { return `/openai/toolsets/${toolset_name}` };

export const getUserBucket = '/v1/bucket';
export const getUserInfo = '/v1/user/info';
export const grantPerRequestPermissions = '/v1/ops/resource/per-request-permissions/grant';
export const listCustomApplicationSchemas = '/v1/application_type_schemas/schemas';
export const listFilesFromCodeInterpreter = '/v1/ops/code_interpreter/list_files';
export const moveResource = '/v1/ops/resource/move';
export const openSession = '/v1/ops/code_interpreter/open_session';
export const rateDeployment = (deployment_name: string) => { return `/v1/${deployment_name}/rate` };

export const redeployApplication = '/v1/ops/application/redeploy';
export const rejectPublication = '/v1/ops/publication/reject';
export const reloadConfig = '/v1/ops/config/reload';
export const requestUserConsent = (deployment_id: string) => { return `/v1/consent/${deployment_id}` };

export const revokePerRequestPermissions = '/v1/ops/resource/per-request-permissions/revoke';
export const revokeSharedResources = '/v1/ops/resource/share/revoke';
export const saveConversation = (bucket: string, conversation_path: string) => { return `/v1/conversations/${bucket}/${conversation_path}` };

export const saveCustomApplication = (bucket: string, application_path: string) => { return `/v1/applications/${bucket}/${application_path}` };

export const savePrompt = (bucket: string, prompt_path: string) => { return `/v1/prompts/${bucket}/${prompt_path}` };

export const saveToolSet = (bucket: string, toolset_path: string) => { return `/v1/toolsets/${bucket}/${toolset_path}` };

export const sendChatCompletionRequest = (deployment_name: string) => { return `/openai/deployments/${deployment_name}/chat/completions` };

export const sendEmbeddingsRequest = (deployment_name: string) => { return `/openai/deployments/${deployment_name}/embeddings` };

export const shareResource = '/v1/ops/resource/share/create';
export const subscribeToResources = '/v1/ops/resource/subscribe';
export const toolSetSignout = '/v1/ops/toolset/signout';
export const toolsetSignin = '/v1/ops/toolset/signin';
export const transferInputFile = '/v1/ops/code_interpreter/transfer_input_file';
export const transferOutputFile = '/v1/ops/code_interpreter/transfer_output_file';
export const undeployApplication = '/v1/ops/application/undeploy';
export const updatePublication = '/v1/ops/publication/update';
export const uploadFile = (bucket: string, file_path: string) => { return `/v1/files/${bucket}/${file_path}` };

export const uploadFileToCodeInterpreter = '/v1/ops/code_interpreter/upload_file';
