/**
 * Path templates (from `openapi.yaml`, one `export const` per `operationId`).
 * Static paths are `as const` strings. Paths with `{param}` are functions: one `string` arg per
 * segment (e.g. `(toolset_name: string) => ...`) or a single object when there are several `{...}` parts.
 *
 * @generated by `scripts/generate-sdk-client.mjs` — do not edit by hand; run `npm run gen`
 */

export const acceptUserConsentUrl = (deployment_id: string) => {
  return `/v1/consent/${deployment_id}`;
};

export const approvePublicationUrl = '/v1/ops/publication/approve';
export const callMcpUrl = (deployment_id: string) => {
  return `/v1/deployments/${deployment_id}/mcp`;
};

export const callToolSetUrl = (toolset_name: string) => {
  return `/v1/toolset/${toolset_name}/mcp`;
};

export const closeSessionUrl = '/v1/ops/code_interpreter/close_session';
export const configurationDeploymentUrl = (deployment_name: string) => {
  return `/v1/deployments/${deployment_name}/configuration`;
};

export const copyResourceUrl = '/v1/ops/resource/copy';
export const copySharedResourcesUrl = '/v1/ops/resource/share/copy';
export const createPublicationUrl = '/v1/ops/publication/create';
export const deleteConversationUrl = (
  bucket: string,
  conversation_path: string,
) => {
  return `/v1/conversations/${bucket}/${conversation_path}`;
};

export const deleteCustomApplicationUrl = (
  bucket: string,
  application_path: string,
) => {
  return `/v1/applications/${bucket}/${application_path}`;
};

export const deleteFileUrl = (bucket: string, file_path: string) => {
  return `/v1/files/${bucket}/${file_path}`;
};

export const deleteInvitationUrl = (invitation_id: string) => {
  return `/v1/invitations/${invitation_id}`;
};

export const deleteNotificationsUrl = '/v1/ops/notification/delete';
export const deletePromptUrl = (bucket: string, prompt_path: string) => {
  return `/v1/prompts/${bucket}/${prompt_path}`;
};

export const deletePublicationUrl = '/v1/ops/publication/delete';
export const deleteToolSetUrl = (bucket: string, toolset_path: string) => {
  return `/v1/toolsets/${bucket}/${toolset_path}`;
};

export const deployApplicationUrl = '/v1/ops/application/deploy';
export const discardSharedResourcesUrl = '/v1/ops/resource/share/discard';
export const downloadFileUrl = (bucket: string, file_path: string) => {
  return `/v1/files/${bucket}/${file_path}`;
};

export const downloadFileFromCodeInterpreterUrl =
  '/v1/ops/code_interpreter/download_file';
export const executeCodeUrl = '/v1/ops/code_interpreter/execute_code';
export const getAllToolSetAllowedToolsUrl = (toolset_id: string) => {
  return `/v1/toolset/${toolset_id}/allowed-tools`;
};

export const getAllToolSetToolsUrl = (toolset_id: string) => {
  return `/v1/toolset/${toolset_id}/tools`;
};

export const getApplicationUrl = (application_name: string) => {
  return `/openai/applications/${application_name}`;
};

export const getApplicationLogsUrl = '/v1/ops/application/logs';
export const getApplicationMetadataUrl = (bucket: string, path: string) => {
  return `/v1/metadata/applications/${bucket}/${path}`;
};

export const getApplicationsUrl = '/openai/applications';
export const getConversationUrl = (
  bucket: string,
  conversation_path: string,
) => {
  return `/v1/conversations/${bucket}/${conversation_path}`;
};

export const getConversationMetadataUrl = (bucket: string, path: string) => {
  return `/v1/metadata/conversations/${bucket}/${path}`;
};

export const getCustomApplicationUrl = (
  bucket: string,
  application_path: string,
) => {
  return `/v1/applications/${bucket}/${application_path}`;
};

export const getCustomApplicationSchemaUrl =
  '/v1/application_type_schemas/schema';
export const getCustomToolSetUrl = (bucket: string, toolset_path: string) => {
  return `/v1/toolsets/${bucket}/${toolset_path}`;
};

export const getDeploymentUrl = (deployment_name: string) => {
  return `/openai/deployments/${deployment_name}`;
};

export const getDeploymentLimitsUrl = (deployment_name: string) => {
  return `/v1/deployments/${deployment_name}/limits`;
};

export const getDeploymentsUrl = '/openai/deployments';
export const getDeploymentsByInterfaceTypeUrl = '/v1/deployments';
export const getFileMetadataUrl = (bucket: string, path: string) => {
  return `/v1/metadata/files/${bucket}/${path}`;
};

export const getInvitationUrl = (invitation_id: string) => {
  return `/v1/invitations/${invitation_id}`;
};

export const getInvitationsUrl = '/v1/invitations';
export const getMetaSchemaOfCustomApplicationSchemaUrl =
  '/v1/application_type_schemas/meta_schema';
export const getModelUrl = (model_name: string) => {
  return `/openai/models/${model_name}`;
};

export const getModelsUrl = '/openai/models';
export const getNotificationsUrl = '/v1/ops/notification/list';
export const getPerRequestPermissionsUrl =
  '/v1/ops/resource/per-request-permissions/list';
export const getPromptUrl = (bucket: string, prompt_path: string) => {
  return `/v1/prompts/${bucket}/${prompt_path}`;
};

export const getPromptMetadataUrl = (bucket: string, path: string) => {
  return `/v1/metadata/prompts/${bucket}/${path}`;
};

export const getPublicationUrl = '/v1/ops/publication/get';
export const getPublicationRulesUrl = '/v1/ops/publication/rule/list';
export const getPublicationsUrl = '/v1/ops/publication/list';
export const getSessionUrl = '/v1/ops/code_interpreter/get_session';
export const getSharedResourcesUrl = '/v1/ops/resource/share/list';
export const getToolSetMetadataUrl = (bucket: string, path: string) => {
  return `/v1/metadata/toolsets/${bucket}/${path}`;
};

export const getToolSetsUrl = '/openai/toolsets';
export const getToolsetUrl = (toolset_name: string) => {
  return `/openai/toolsets/${toolset_name}`;
};

export const getUserBucketUrl = '/v1/bucket';
export const getUserInfoUrl = '/v1/user/info';
export const grantPerRequestPermissionsUrl =
  '/v1/ops/resource/per-request-permissions/grant';
export const interactWithClientChannelUrl = '/v1/ops/client-channel/interact';
export const listCustomApplicationSchemasUrl =
  '/v1/application_type_schemas/schemas';
export const listFilesFromCodeInterpreterUrl =
  '/v1/ops/code_interpreter/list_files';
export const moveResourceUrl = '/v1/ops/resource/move';
export const openSessionUrl = '/v1/ops/code_interpreter/open_session';
export const rateDeploymentUrl = (deployment_name: string) => {
  return `/v1/${deployment_name}/rate`;
};

export const redeployApplicationUrl = '/v1/ops/application/redeploy';
export const rejectPublicationUrl = '/v1/ops/publication/reject';
export const reloadConfigUrl = '/v1/ops/config/reload';
export const reportResponseToClientChannelUrl = '/v1/ops/client-channel/report';
export const requestUserConsentUrl = (deployment_id: string) => {
  return `/v1/consent/${deployment_id}`;
};

export const revokePerRequestPermissionsUrl =
  '/v1/ops/resource/per-request-permissions/revoke';
export const revokeSharedResourcesUrl = '/v1/ops/resource/share/revoke';
export const saveConversationUrl = (
  bucket: string,
  conversation_path: string,
) => {
  return `/v1/conversations/${bucket}/${conversation_path}`;
};

export const saveCustomApplicationUrl = (
  bucket: string,
  application_path: string,
) => {
  return `/v1/applications/${bucket}/${application_path}`;
};

export const savePromptUrl = (bucket: string, prompt_path: string) => {
  return `/v1/prompts/${bucket}/${prompt_path}`;
};

export const saveToolSetUrl = (bucket: string, toolset_path: string) => {
  return `/v1/toolsets/${bucket}/${toolset_path}`;
};

export const sendChatCompletionRequestUrl = (deployment_name: string) => {
  return `/openai/deployments/${deployment_name}/chat/completions`;
};

export const sendEmbeddingsRequestUrl = (deployment_name: string) => {
  return `/openai/deployments/${deployment_name}/embeddings`;
};

export const shareResourceUrl = '/v1/ops/resource/share/create';
export const subscribeOnClientChannelUrl = '/v1/ops/client-channel/subscribe';
export const subscribeToResourcesUrl = '/v1/ops/resource/subscribe';
export const toolSetSignoutUrl = '/v1/ops/toolset/signout';
export const toolsetSigninUrl = '/v1/ops/toolset/signin';
export const transferInputFileUrl =
  '/v1/ops/code_interpreter/transfer_input_file';
export const transferOutputFileUrl =
  '/v1/ops/code_interpreter/transfer_output_file';
export const undeployApplicationUrl = '/v1/ops/application/undeploy';
export const unsubscribeOnClientChannelUrl =
  '/v1/ops/client-channel/unsubscribe';
export const updatePublicationUrl = '/v1/ops/publication/update';
export const uploadFileUrl = (bucket: string, file_path: string) => {
  return `/v1/files/${bucket}/${file_path}`;
};

export const uploadFileToCodeInterpreterUrl =
  '/v1/ops/code_interpreter/upload_file';
